import { ExamPaperGenerationCore } from './exam-paper-generation.core';

describe('ExamPaperGenerationCore', () => {
  const core = new ExamPaperGenerationCore();
  const question = (id: number, difficulty: string, score?: number) => ({ id, difficulty, score });

  it('selects the requested count from each difficulty pool', () => {
    const selected = core.selectByCount(
      { easy: [question(1, 'EASY'), question(2, 'EASY')], medium: [question(3, 'MEDIUM')], hard: [question(4, 'HARD')] },
      { easy: 1, medium: 1, hard: 1 },
    );
    expect(selected).toHaveLength(3);
    expect(selected.map((item) => item.difficulty).sort()).toEqual(['EASY', 'HARD', 'MEDIUM']);
  });

  it('selects an exact score when the pool can satisfy it', () => {
    const selected = core.selectByScore([question(1, 'EASY', 1), question(2, 'EASY', 2), question(3, 'EASY', 3)], 3, 1);
    expect(selected.reduce((sum, item) => sum + Number(item.score || 1), 0)).toBe(3);
  });

  it('normalizes count-based scores to ten points for multiple choice', () => {
    const result = core.assignScores([question(1, 'EASY'), question(2, 'HARD')], {
      targetType: 'TRAC_NGHIEM',
      isEssay: false,
      isByScore: false,
    });
    expect(result.totalScore).toBe(10);
    expect(result.questions.reduce((sum, item) => sum + item.assignedScore, 0)).toBe(10);
  });

  it('preserves actual question scores for essay exam', () => {
    const questions = [
      question(1, 'EASY', 2.0),
      question(2, 'EASY', 2.0),
      question(3, 'EASY', 2.0),
      question(4, 'MEDIUM', 2.0),
      question(5, 'MEDIUM', 2.0),
    ];
    const result = core.assignScores(questions, {
      targetType: 'TU_LUAN',
      isEssay: true,
      isByScore: false,
    });
    expect(result.totalScore).toBe(10.0);
    result.questions.forEach((q) => {
      expect(q.assignedScore).toBe(2.0);
    });
  });

  it('normalizes custom individual scores for essay exam proportionally to exact 10 points when generated by count', () => {
    const questions = [
      question(1, 'EASY', 1.5),
      question(2, 'MEDIUM', 3.0),
      question(3, 'HARD', 4.0),
    ];
    const result = core.assignScores(questions, {
      targetType: 'TU_LUAN',
      isEssay: true,
      isByScore: false,
    });
    expect(result.totalScore).toBe(10.0);
    const sum = result.questions.reduce((s, q) => s + q.assignedScore, 0);
    expect(sum).toBe(10.0);
  });

  it('preserves target scores when generated by score (BY_SCORE)', () => {
    const questions = [
      {
        id: 1,
        difficulty: 'EASY',
        score: 2.0,
        fillBlankAnswers: [{ blankIndex: 1, score: 1.0 }, { blankIndex: 2, score: 1.0 }],
      },
      {
        id: 2,
        difficulty: 'MEDIUM',
        score: 3.0,
        fillBlankAnswers: [{ blankIndex: 1, score: 1.5 }, { blankIndex: 2, score: 1.5 }],
      },
    ];
    const result = core.assignScores(questions, {
      targetType: 'FILL_BLANK',
      isEssay: false,
      isByScore: true,
    });
    expect(result.totalScore).toBe(5.0);
    expect(result.questions[0].assignedScore).toBe(2.0);
    expect(result.questions[1].assignedScore).toBe(3.0);
  });

  it('selectByCount smartly finds the question combination summing up to 10 points using real scores', () => {
    const easyPool = [
      question(1, 'EASY', 1.0),
      question(2, 'EASY', 2.0),
      question(3, 'EASY', 2.0),
      question(4, 'EASY', 1.0),
    ];
    const medPool = [
      question(5, 'MEDIUM', 3.0),
      question(6, 'MEDIUM', 1.0),
      question(7, 'MEDIUM', 3.0),
    ];
    // Select 3 Easy + 2 Medium: e.g. Easy (2.0 + 2.0 + 1.0 = 5.0) + Medium (3.0 + 2.0? No, 3.0 + 2.0 not available, 3.0 + 3.0? No, 2+2+1=5, wait 2+2+0? 2+1+1=4 and 3+3=6 -> 4+6=10!)
    const selected = core.selectByCount(
      { easy: easyPool, medium: medPool, hard: [] },
      { easy: 3, medium: 2, hard: 0 },
      { targetScore: 10.0, isEssay: true },
    );
    expect(selected).toHaveLength(5);
    const sum = selected.reduce((s, q) => s + core.getRealScore(q, true), 0);
    expect(sum).toBe(10.0);
  });
});
