'use client';
import { useState } from 'react';
import api from '../../lib/api';
import { Modal } from '../Modal';
export function QuestionImportWizard({ open, onClose, onDone }: { open: boolean; onClose: () => void; onDone: () => void }) {
  const [file, setFile] = useState<File | null>(null); const [preview, setPreview] = useState<any>(null); const [selected, setSelected] = useState<number[]>([]); const [busy, setBusy] = useState(false);
  const template = async () => { const r = await api.get('/questions/import/template', { responseType: 'blob' }); const url = URL.createObjectURL(r.data); const a = document.createElement('a'); a.href = url; a.download = 'question-import-template.csv'; a.click(); URL.revokeObjectURL(url); };
  const load = async () => { if (!file) return; setBusy(true); try { const f = new FormData(); f.append('file', file); const r = await api.post('/questions/import/preview', f); setPreview(r.data); setSelected(r.data.rows.filter((x:any) => !x.errors.length).map((x:any) => x.row)); } finally { setBusy(false); } };
  const confirm = async () => { if (!file || !preview) return; setBusy(true); try { const f = new FormData(); f.append('file', file); f.append('hash', preview.hash); f.append('rows', JSON.stringify(selected)); await api.post('/questions/import/confirm', f); onDone(); onClose(); } finally { setBusy(false); } };
  return <Modal isOpen={open} onClose={onClose} title="Import CSV: Upload → Preview → Confirm"><div className="space-y-4"><div className="flex gap-2"><input type="file" accept=".csv" onChange={e => { setFile(e.target.files?.[0] || null); setPreview(null); }} /><button onClick={template} className="text-sky-700">Tải mẫu CSV</button><button disabled={!file || busy} onClick={load} className="rounded-lg bg-sky-600 px-3 py-1 text-white">Xem trước</button></div>{preview && <div className="max-h-80 space-y-2 overflow-auto">{preview.rows.map((r:any) => <label key={r.row} className="flex gap-2 rounded-lg border p-2 text-sm"><input type="checkbox" disabled={r.errors.length} checked={selected.includes(r.row)} onChange={e => setSelected(e.target.checked ? [...selected,r.row] : selected.filter(x => x !== r.row))} /><span>Dòng {r.row}: {r.data.content}<small className="block text-rose-600">{r.errors.join(', ')}{r.duplicates.length ? ' · Trùng nội dung' : ''}</small></span></label>)}</div>}{preview && <button disabled={!selected.length || busy} onClick={confirm} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Xác nhận nhập {selected.length} câu nháp</button>}</div></Modal>;
}
