'use client';
import { useState } from 'react';
import api from '../../lib/api';
import { Subject } from '../../types';
import { Modal } from '../Modal';
export function QuestionAIWizard({ open, subjects, onClose, onDone }: { open: boolean; subjects: Subject[]; onClose: () => void; onDone: () => void }) {
  const [form, setForm] = useState({ subjectId: '', chapterId: '', type: 'SINGLE_CHOICE', difficulty: 'MEDIUM', bloomLevel: 'UNDERSTAND', count: 5, prompt: '' }); const [items, setItems] = useState<any[]>([]); const [busy, setBusy] = useState(false);
  const subject = subjects.find(s => String(s.id) === form.subjectId); const set = (k:string,v:any) => setForm(p => ({ ...p, [k]:v, ...(k === 'subjectId' ? { chapterId: '' } : {}) }));
  const generate = async () => { setBusy(true); try { const r = await api.post('/questions/ai-generate', { ...form, subjectId:Number(form.subjectId), count:Number(form.count) }); setItems(r.data); } finally { setBusy(false); } };
  const save = async () => { setBusy(true); try { await api.post('/questions/ai-save', { questions: items.map(({ duplicate, ...q }) => q) }); onDone(); onClose(); } finally { setBusy(false); } };
  return <Modal isOpen={open} onClose={onClose} title="AI Wizard"><div className="space-y-3"><div className="grid grid-cols-2 gap-2"><select value={form.subjectId} onChange={e => set('subjectId',e.target.value)} className="rounded-lg border p-2"><option value="">Chọn môn</option>{subjects.map(s => <option key={s.id} value={s.id}>{s.subjectName}</option>)}</select><select value={form.chapterId} onChange={e => set('chapterId',e.target.value)} className="rounded-lg border p-2"><option value="">Chọn chương</option>{subject?.chapters?.map(c => <option key={c.id} value={c.id}>{c.name}</option>)}</select><select value={form.type} onChange={e => set('type',e.target.value)} className="rounded-lg border p-2"><option>SINGLE_CHOICE</option><option>MULTIPLE_CHOICE</option><option>TRUE_FALSE</option><option>FILL_BLANK</option><option>ESSAY</option></select><select value={form.difficulty} onChange={e => set('difficulty',e.target.value)} className="rounded-lg border p-2"><option>EASY</option><option>MEDIUM</option><option>HARD</option></select><select value={form.bloomLevel} onChange={e => set('bloomLevel',e.target.value)} className="rounded-lg border p-2"><option>REMEMBER</option><option>UNDERSTAND</option><option>APPLY</option><option>ANALYZE</option></select><input type="number" min="1" max="20" value={form.count} onChange={e => set('count',e.target.value)} className="rounded-lg border p-2" /></div><textarea value={form.prompt} onChange={e => set('prompt',e.target.value)} placeholder="Chủ đề hoặc nội dung tham khảo" className="w-full rounded-lg border p-2" /><button disabled={busy || !form.chapterId} onClick={generate} className="rounded-xl bg-violet-600 px-4 py-2 text-white">Tạo câu hỏi thật bằng Gemini</button>{items.map((q,i) => <textarea key={i} value={q.content} onChange={e => setItems(items.map((x,j) => j===i ? {...x,content:e.target.value}:x))} className="w-full rounded-lg border p-2" />)}{items.length > 0 && <button disabled={busy} onClick={save} className="rounded-xl bg-emerald-600 px-4 py-2 text-white">Lưu {items.length} câu vào DRAFT</button>}</div></Modal>;
}
